---

- name: Install accounting packages
  ansible.builtin.package:
    name: "{{ accounting_packages }}"
    state: present

- name: Start accounting
  ansible.builtin.service:
    name: "{{ accounting_service }}"
    state: started
    enabled: true

- name: Set appropiate permissions
  ansible.builtin.file:
    path: "{{ accounting_file }}"
    owner: root
    mode: "0644"
